---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end.canary
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        pipeline.stage: prod-canary
        pipeline.build: 1.5.0.3486
        pipeline.project: sockshop
        support.contact: "jane.smith@sockshop.com"
        support.channel: "#support-sockshop-frontend"
      labels:
        app: front-end.canary
        stage: dev
        release: canary
        version: "1.5"
        tier: "frontend"
        product: "sockshop"
    spec:
      containers:
      - name: front-end
        image: dynatracesockshop/front-end:0.5.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      hostAliases:
        - hostnames:
            - gfc07687.live.dynatrace.com
            - sg-ap-southeast-2-52-65-159-6-prod40-sydney.live.ruxit.com
          ip: 52.65.159.6
        - hostnames:
            - sg-ap-southeast-2-3-105-220-233-prod40-sydney.live.ruxit.com
          ip: 3.105.220.233
        - hostnames:
            - sg-ap-southeast-2-3-106-36-21-prod40-sydney.live.ruxit.com
          ip: 3.106.36.21           
      nodeSelector:
        beta.kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: front-end-canary
  labels:
    app: front-end.canary
    namespace: dev
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: front-end.canary
  type: LoadBalancer
