---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "false"
        dynatrace/instrument: "false"
        pipeline.stage: prod-stable
        pipeline.build: 1.0.1.0005
        pipeline.project: sockshop
        support.contact: "jimmy.page@sockshop.com"
        support.channel: "#support-sockshop-middleware"
      labels:
        name: rabbitmq
        stage: prod
        version: "1.0"
        tier: messaging
        product: sockshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
      hostAliases:
        - hostnames:
            - gfc07687.live.dynatrace.com
            - sg-ap-southeast-2-52-65-159-6-prod40-sydney.live.ruxit.com
          ip: 52.65.159.6
        - hostnames:
            - sg-ap-southeast-2-3-105-220-233-prod40-sydney.live.ruxit.com
          ip: 3.105.220.233
        - hostnames:
            - sg-ap-southeast-2-3-106-36-21-prod40-sydney.live.ruxit.com
          ip: 3.106.36.21          
      nodeSelector:
        beta.kubernetes.io/os: linux